---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-testing
  namespace: openshift-cnv
  labels:
    kubevirt.io: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-testing-cluster-admin
  labels:
    kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubevirt-testing
    namespace: openshift-cnv
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disks-images-provider
  namespace: openshift-cnv
  labels:
    kubevirt.io: "disks-images-provider"
spec:
  selector:
    matchLabels:
      kubevirt.io: "disks-images-provider"
  template:
    metadata:
      labels:
        name: disks-images-provider
        kubevirt.io: disks-images-provider
      name: disks-images-provider
    spec:
      serviceAccountName: kubevirt-testing
      containers:
        - name: target
          image: quay.io/kubevirt/disks-images-provider:__KUBEVIRT_RELEASE__
          imagePullPolicy: Always
          env:
            - name: NUM_TEST_IMAGE_REPLICAS
              value: "8"
          volumeMounts:
          - name: images
            mountPath: /hostImages
          - name: local-storage
            mountPath: /local-storage
          - name: host-dir
            mountPath: /host
            mountPropagation: Bidirectional
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          readinessProbe:
            exec:
              command:
              - cat
              - /ready
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: images
          hostPath:
            path: /tmp/hostImages
            type: DirectoryOrCreate
        - name: local-storage
          hostPath:
            path: /mnt/local-storage
            type: DirectoryOrCreate
        - name: host-dir
          hostPath:
            path: /